# Generated by Django 5.1.4 on 2025-02-02 00:24

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='SELLER', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='seller_images')),
                ('business_category', models.CharField(choices=[('WHOLE_SELLER', 'Whole Seller'), ('SUPPLIER', 'Supplier'), ('RETAILER', 'Retailer'), ('FARMER', 'Farmer')], default='FARMER', max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_premium', models.BooleanField(default=False, null=True)),
                ('premium_subscription_expiry', models.DateField(blank=True, null=True)),
                ('business_description', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('social_media_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('preferred_payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('bank_account_details', models.JSONField(blank=True, null=True)),
                ('county', models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Kiambu', 'Kiambu'), ('Meru', 'Meru'), ('Kericho', 'Kericho'), ('Nyeri', 'Nyeri'), ('Embu', 'Embu'), ('Kakamega', 'Kakamega'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Kilifi', 'Kilifi'), ('Malindi', 'Malindi'), ('Limuru', 'Limuru'), ('Naivasha', 'Naivasha'), ('Lamu', 'Lamu'), ('Thika', 'Thika'), ('Voi', 'Voi'), ('Kapsabet', 'Kapsabet'), ('Kisii', 'Kisii'), ('Homa Bay', 'Homa Bay'), ('Busia', 'Busia'), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Samburu', 'Samburu'), ('West Pokot', 'West Pokot'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nyandarua', 'Nyandarua'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Kitui', 'Kitui'), ('Tana River', 'Tana River'), ('Taita Taveta', 'Taita Taveta'), ('Transnzoia', 'Trans nzoia')], max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('total_products_sold', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], default='BUYER', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('bio', models.TextField(blank=True, null=True)),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_county', models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Kiambu', 'Kiambu'), ('Meru', 'Meru'), ('Kericho', 'Kericho'), ('Nyeri', 'Nyeri'), ('Embu', 'Embu'), ('Kakamega', 'Kakamega'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Kilifi', 'Kilifi'), ('Malindi', 'Malindi'), ('Limuru', 'Limuru'), ('Naivasha', 'Naivasha'), ('Lamu', 'Lamu'), ('Thika', 'Thika'), ('Voi', 'Voi'), ('Kapsabet', 'Kapsabet'), ('Kisii', 'Kisii'), ('Homa Bay', 'Homa Bay'), ('Busia', 'Busia'), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Samburu', 'Samburu'), ('West Pokot', 'West Pokot'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nyandarua', 'Nyandarua'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Kitui', 'Kitui'), ('Tana River', 'Tana River'), ('Taita Taveta', 'Taita Taveta'), ('Transnzoia', 'Trans nzoia')], max_length=80, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('preferred_payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('preferred_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('language_preference', models.CharField(default='English', max_length=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('addresses', models.JSONField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating_given', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
    ]
