# Generated by Django 5.1.4 on 2025-01-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_default_county'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_county',
            field=models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Kiambu', 'Kiambu'), ('Meru', 'Meru'), ('Kericho', 'Kericho'), ('Nyeri', 'Nyeri'), ('Embu', 'Embu'), ('Kakamega', 'Kakamega'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Kilifi', 'Kilifi'), ('Malindi', 'Malindi'), ('Limuru', 'Limuru'), ('Naivasha', 'Naivasha'), ('Lamu', 'Lamu'), ('Thika', 'Thika'), ('Voi', 'Voi'), ('Kapsabet', 'Kapsabet'), ('Kisii', 'Kisii'), ('Homa Bay', 'Homa Bay'), ('Busia', 'Busia'), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Samburu', 'Samburu'), ('West Pokot', 'West Pokot'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nyandarua', 'Nyandarua'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Kitui', 'Kitui'), ('Tana River', 'Tana River'), ('Taita Taveta', 'Taita Taveta'), ('Transnzoia', 'Trans nzoia')], max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(max_length=12, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
