# Generated by Django 5.1.4 on 2025-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_default_county_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
