# Generated by Django 5.1.4 on 2025-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20230319_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
